sudo: required

services:
  - docker

install:
  - docker build -t juank/postgis:10 .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push juank/postgis:10;
    fi
