sudo: required

services:
  - docker

install:
  - docker build -t juank/postgis:10 .

before_script:
  - docker run -d -e POSTGRES_USER=test -e POSTGRES_PASSWORD=test -e POSTGRES_DB=test -p 5433:5432 juank/postgis:10

script:
  - PGPASSWORD=$POSTGRES_PASSWORD psql -h 127.0.0.1 -p 5433 -u $POSTGRES_USER -d $POSTGRES_DB -c "SELECT POSTGIS_VERSION();"

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      docker push juank/postgis:10;
    fi
