sudo: required

services:
  - docker

before_install:
  - sudo apt-get install wget ca-certificates
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
  - sudo apt-get remove postgresql-* -y
  - sudo apt-get update -q
  - sudo apt-get install postgresql-client-10

install:
  - docker build -t juank/postgis:10 .

before_script:
  - docker run --privileged --name test_postgis -d -e POSTGRES_USER=$POSTGRES_USER -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD -e POSTGRES_DB=$POSTGRES_DB -p 5433:5432 juank/postgis:10

script:
  - PGPASSWORD=$POSTGRES_PASSWORD psql -h 127.0.0.1 -p 5433 -U $POSTGRES_USER -d $POSTGRES_DB -c "SELECT POSTGIS_VERSION();"

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      docker push juank/postgis:10;
    fi

after_failure:
  - docker ps -a
  - docker logs test_postgis