sudo: required

services:
  - docker

before_install:
  - export TAG=latest

install:
  - docker build -t juank/postgis:$TAG .

before_script:
  - docker run --name test_postgis -d -e POSTGRES_USER=$POSTGRES_USER -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD -e POSTGRES_DB=$POSTGRES_DB -p 127.0.0.1:5433:5432 juank/postgis:$TAG
  - sleep 15

script:
  - PGPASSWORD=$POSTGRES_PASSWORD psql -h 127.0.0.1 -p 5433 -U $POSTGRES_USER -d $POSTGRES_DB -c "SELECT POSTGIS_VERSION();"

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  - docker push juank/postgis:$TAG;

after_failure:
  - docker logs test_postgis
